name: Build & Deploy ZIP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Build release.zip
        run: |
          zip -r release.zip \
            popup.html \
            background.js \
            popup.js \
            style.css \
            manifest.json \
            icon.png

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_files: release.zip
          commit_message: Update release.zip
