name: Build & Deploy ZIP to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Build release.zip
        run: |
          zip -r release.zip \
            popup.html \
            background.js \
            popup.js \
            style.css \
            manifest.json \
            icon.png

      - name: Setup Git
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Clone gh-pages branch
        run: |
          git clone --single-branch --branch gh-pages https://github.com/${{ github.repository }}
          cd pages
          cp ../release.zip .
          git add release.zip
          git commit -m "Update release.zip"
          git push origin gh-pages
