name: Build ZIP & Push to releases branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from main
        uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Build release.zip
        run: |
          zip -r release.zip \
            popup.html \
            background.js \
            popup.js \
            style.css \
            manifest.json \
            icon.png

      - name: Clone releases branch
        run: |
          git clone --single-branch --branch releases https://github.com/Risaro/garage-proxy releases
          cd releases
          cp ../release.zip .
          git add release.zip

      - name: Commit and Push to releases branch
        run: |
          cd releases
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git commit -m "Update release.zip" || echo "No changes in release.zip"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Risaro/garage-proxy
          git push origin releases --force
